services:
  - type: web
    name: clashpilot-license-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EMAIL_PASSWORD
        sync: false  # تتم إضافتها يدويًا من لوحة تحكم Render
