services:
  - type: web
    name: clashpilot-license-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    plan: free
    envVars:
      - key: EMAIL_PASSWORD
        sync: false  # تتم إضافتها يدويًا من لوحة التحكم في Render
