services:
  - type: web
    name: clashpilot-license-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: EMAIL_PASSWORD
        sync: false
